@startuml
!pragma teoz true
/'Defines the protocol when a user wants to change their password using the changePassword() routine'/
/'author: Luvai Cutlerywala <luvaidc@gmail.com>'/

/'Define the actors and participants.'/
actor User as user

box UI
    participant "Web UI" as web_ui
    participant "Mobile App" as mobile_app
end box

box Backend
    control "Service Manager" as service_manager

    box Listener
        queue "Listener\nQueue" as listener_queue
        participant "Listener" as listener
    end box

    participant "Scheduler" as scheduler
    participant "Deliverability\nTest" as deliverability_test
    participant "Deliverability\nTest Log" as deliverability_test_log
    participant "Messaging\nService" as messenger
    participant "Deliverability\nTest Phones" as deliverability_test_phones
    participant "Report\nGeneration Service" as report_generator
    participant "Authentication\nService" as auth
end box

box Database
    database "deliverability_test" as dt
    database "deliverability_\ntest_logs" as dtl
    database "deliverability_\ntest_phones" as dtp
    database clients as clients
    database clients_log as cl
end box

box "Broker API"
    participant "Bandwidth API" as broker_api
end box

web_ui -> service_manager: New password for {client_id, session_token_id}
service_manager -> auth: New password for {client_id, session_token_id}
auth -> cl: Does {session_token_id} exist?
cl --> auth: {session_token_id, session_metadata}
auth -> clients: Update password for {client_id}
auth -> cl: Signed out at {current_date_time, session_token_id, client_id}
auth --> service_manager: Client signed out
service_manager --> web_ui: Client signed out
web_ui --> user: Please sign-in again with new password

@enduml