@startuml
!pragma teoz true

/'Defines the protocol when a user submits a request to create and execute a test immediately.'/
/'author: Luvai Cutlerywala <luvaidc@gmail.com>'/

/'Define the actors and participants.'/
actor User as user

box UI
    participant "Web UI" as web_ui
    participant "Mobile App" as mobile_app
end box

box Backend
    control "Service Manager" as service_manager

    box Listener
        queue "Listener\nQueue" as listener_queue
        participant "Listener" as listener
    end box

    participant "Scheduler" as scheduler
    participant "Deliverability\nTest" as deliverability_test
    participant "Deliverability\nTest Log" as deliverability_test_log
    participant "Messaging\nService" as messenger
    participant "Deliverability\nTest Phones" as deliverability_test_phones
    participant "Report\nGeneration Service" as report_generator
    participant "Authentication\nService" as auth
end box

box Database
    database "deliverability_test" as dt
    database "deliverability_\ntest_logs" as dtl
    database "deliverability_\ntest_phones" as dtp
    database clients as clients
    database clients_log as cl
end box

box "Broker API"
    participant "Bandwidth API" as broker_api
end box

box "Broker API"
    participant "Bandwidth API" as broker_api
end box

user -> web_ui: Create test with {test_metadata}, to be run now.
web_ui -> service_manager: Create test with {test_metadata}, to be run now.
service_manager -> deliverability_test: Create test with {test_metadata}.
activate deliverability_test
deliverability_test -> dt: Insert record with {test_id, test_metadata}.
deliverability_test --> service_manager: Test created, {test_id}.
deactivate deliverability_test
service_manager -> deliverability_test_log: Initiate test with {test_id, test_metadata}.
activate deliverability_test_log
loop Insert initiated test records for each phone number in test
    deliverability_test_log -> dtl: Insert record with {test_log_id, test_id, test_metadata}.
    deliverability_test_log --> service_manager: Test initiated, {test_log_id}.
end loop
deactivate deliverability_test_log
service_manager -> service_manager: executeTest()
@enduml
