@startuml
start
:User creates a test;
:Test data is sent to the Service Manager;
:Service Manager triggers the scheduler to schedule the test \naccording to the date and time that the user has provided;
:Service Manager triggers the Deliverability Test Service to create a test and update the database with new test;
if (Time is 10 seconds to test?) then (yes)
    :Scheduler triggers the Service Manager;
    :Service Manager triggers Deliverability Test Log Service to initiate test;
    :Service Manager triggers the Messaging Service to trigger message send off;
    :Messaging Service responds with data about message, i.e. sent or failed;
    :Service Manager triggers Deliverability Test Log Service to update the test data;
else (no)
endif

stop
@enduml