@startuml

/'author: Bushra Attarwala <bushraattarwala15@gmail.com>'/
start
:User Logs in;
  :Create Test;
  :Insert record in deliverability_test table;
  if (Scheduled?) then (yes)
    :Add test to Listener Queue;
    :Insert test in deliverability_test_logs;
    if (recurring?) then (yes)
      repeat :For all tests scheduled;
        :Insert test in deliverability_test_logs;
      repeat while (next schedule)
    else (singleton)
      stop
    end if
  else (no)
    :Service manager initiates test;
    :Insert record in deliverability_test_logs;
    :Service manager executes test;
  end if

stop
@enduml
