@startuml

/'Defines all the components in the diagram, including the actor.'/ 
User as user

package UI {
    component "Web UI" as web_ui
    component "Mobile App" as mobile_app
}

node "Application Server" {
    package "Service Manager"{
      component "External API" as ext
      component "Service Manager" as service_manager
      component "Service API" as api
    }

    package "Schedulers" {
        component "Text Execution Scheduler" as text_exec_scheduler
        component "Send Message Scheduler" as send_msg_scheduler
    }

    component "Deliverability Test Log Service" as dtl_service
    component "Deliverability Test Service" as dt_service
    component "Deliverability Test Phones Service" as dtp_service
    component "Report Generation Service" as rg_service
    component "Messaging Service" as messenger
    component "Authentication Service" as auth
}

cloud "Aggregator API" {
    interface "Bandwidth API" as bandwidth
}

database Database {
    skinparam componentStyle rectangle
    database deliverability_test as dt
    database deliverability_test_logs as dtl
    database deliverability_test_phones as dtp
    database deliverability_test_users as dtu
    skinparam componentStyle uml2
}

/'Defines the interactions between the components in the diagram.'/ 

/'Frontend Interactions'/ 
user -- web_ui
user -- mobile_app
web_ui -- ext
mobile_app -- ext

/'Backend Interactions'/ 
ext -- service_manager
service_manager -- api

api -- text_exec_scheduler
api-- send_msg_scheduler
api -- dt_service
api -- dtl_service
api -- rg_service
api -- messenger
api -- auth
api -- dtp_service

/'Database Interactions'/ 
dtp_service -- dtp
dtl_service -- dtl
dt_service -- dt
auth -- dtu
rg_service -- dt

/'Third Party Interactions'/ 
bandwidth -- messenger

@enduml
